stages:
  - build
  - test
  - containerize
  - deploy

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  CONTAINER_IMAGE: $CI_REGISTRY_IMAGE:latest

build:
  stage: build
  image: registry.gitlab.com/coverified/infrastructure/scala-base:latest
  script:
    - ./gradlew shadowJar --no-daemon
  artifacts:
    paths:
      - build/libs/

scalatest:
  stage: test
  image: registry.gitlab.com/coverified/infrastructure/scala-base:latest
  script:
    - ./gradlew scalatest --no-daemon
  artifacts:
    reports:
      junit: build/reports/tests/xml/*.xml

containerize:
  stage: containerize
  image: docker:20
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull -t $CONTAINER_IMAGE .
    - docker push $CONTAINER_IMAGE

# TODO: run tests
#test1:
#  stage: test
#  script:
#    - docker pull $CONTAINER_TEST_IMAGE
#    - docker run $CONTAINER_TEST_IMAGE /script/to/run/tests
#
#test2:
#  stage: test
#  script:
#    - docker pull $CONTAINER_TEST_IMAGE
#    - docker run $CONTAINER_TEST_IMAGE /script/to/run/another/test

# TODO: deployment
#deploy:
#  stage: deploy
#  script:
#    - ./deploy.sh
#  only:
#    - master
